### ISSUE TITLE
Buttons Not Working

### ISSUE THREAD

**Issue by BhagavatiAntala** [wppconnect-team/wa-js#1192] opened 2023-06-21 05:25 UTC
iOS -> WhatsappBusiness
When I try to send buttons not display on receiver's Web Whatsapp and not in mobile.

**Comment by edgardmessias** [comment] 2023-06-21 11:14
The buttons are deprecated, the Meta blocked it

Duplicate of #905

**Closed by edgardmessias** 2023-06-21 11:14 UTC
Labels: bug, needs triage
