### ISSUE TITLE
Same issue as #1699 but i am using latest whatsapp-js version  (v3.0.0) but it' not working at all.

### ISSUE THREAD

**Issue by harvansh265** [wppconnect-team/wa-js#1744] opened 2024-03-15 15:10 UTC
Code injected successfully and also WPP variable is their but when i call any function from injected  file its throwing error
  
**Environment**

- **Web WhatsApp version:** 2.3000.1012082673 (joined beta)
- **WA-JS version(s):** 3.0.0
- **Browser:** Chrome 122.0.6261.113 (Official Build) (64-bit)
- **OS:** Windows

![WhatsApp Image 2024-03-15 at 8 23 46 PM](https://github.com/wppconnect-team/wa-js/assets/43061641/c00a609d-f48a-4dc1-a104-37c29013ed44)

**Comment by fancywhat** [comment] 2024-03-18 03:00
same
![0f6fc1f4871a07a95275f9f741c846b1](https://github.com/wppconnect-team/wa-js/assets/50398009/606a3a45-b0e8-4000-b672-68a238f5d641)
![b8544dbd6251e29bdeec498e09aeb6a3](https://github.com/wppconnect-team/wa-js/assets/50398009/425a3f5c-9189-43e4-ab26-60d73d209c4e)

**Comment by fancywhat** [comment] 2024-03-18 03:02
my WhatsApp version is 2.3000, but in WhatsApp 2.24 version, there is no errors at all

**Comment by kakaPup** [comment] 2024-03-18 03:24
The same issue has been encountered by me as well, and I would appreciate your assistance in resolving it.

**Comment by rungogogo** [comment] 2024-03-18 03:30
I've encountered the same issue, do you have any solutions?

**Comment by wangchunself** [comment] 2024-03-18 03:37
I've encountered the same issue as well. I'm unsure of the current progress made by the developers or if there's any iteration plan in place.

**Comment by ZengYongxin-ECJTU** [comment] 2024-03-18 05:42
Last week I also encountered a similar issue , do you have any effective solutions?

**Comment by edgardmessias** [comment] 2024-03-18 11:17
Guys, could you check the value of `WPP.isInjected` and `WPP.isReady`?

The error 'reading m' is caused by to try running some code before the injection

**Comment by fancywhat** [comment] 2024-03-19 06:11
> Guys, could you check the value of `WPP.isInjected` and `WPP.isReady`?
> 
> The error 'reading m' is caused by to try running some code before the injection

This problem is currently an occasional problem on my plugin, and it is true that `WPP.isReady `and `WPP.isInjected `are `false` when there is an error, it is normal to refresh the page multiple times, but this is only in WhatsApp version 2.30, I tried repeatedly on version 2.24 of WhatsApp, and the same set of code will not have similar errors

**Comment by rzlnhd** [comment] 2024-03-19 07:14
> > Guys, could you check the value of `WPP.isInjected` and `WPP.isReady`?
> > The error 'reading m' is caused by to try running some code before the injection
> 
> This problem is currently an occasional problem on my plugin, and it is true that `WPP.isReady `and `WPP.isInjected `are `false` when there is an error, it is normal to refresh the page multiple times, but this is only in WhatsApp version 2.30, I tried repeatedly on version 2.24 of WhatsApp, and the same set of code not have similar errors

How can u roll back to WhatsApp version 2.24? Or it can't?

**Comment by wangchunself** [comment] 2024-03-19 07:19
> > > Guys, could you check the value of `WPP.isInjected` and `WPP.isReady`?
> > > The error 'reading m' is caused by to try running some code before the injection
> > 
> > 
> > This problem is currently an occasional problem on my plugin, and it is true that `WPP.isReady `and `WPP.isInjected `are `false` when there is an error, it is normal to refresh the page multiple times, but this is only in WhatsApp version 2.30, I tried repeatedly on version 2.24 of WhatsApp, and the same set of code not have similar errors
> 
> How can u roll back to WhatsApp version 2.24? Or it can't?

Whatsapp version cannot be rolled back. The phenomenon I have here is that some devices have not been updated, so they are version 2.24. As mentioned above, I also have problems with some accounts in the same 2.30 version. Not all 2.30 versions have problems, but 2.24 There were no problems overall.

**Comment by fancywhat** [comment] 2024-03-19 09:59
> Guys, could you check the value of `WPP.isInjected` and `WPP.isReady`?
> 
> The error 'reading m' is caused by to try running some code before the injection

when `WPP.isInjected` is `false`, how can i reload WPP util `WPP.isInjected` is `true`

**Comment by icleitoncosta** [comment] 2024-03-23 11:17
> I've encountered the same issue as well. I'm unsure of the current progress made by the developers or if there's any iteration plan in place.

What's the way you're injecting? Playwright or extension?
Could you provide the code you use for injection to be able to replicate the errors here and solve this?

**Comment by ono77** [comment] 2024-03-27 11:25
> What's the way you're injecting? Playwright or extension? Could you provide the code you use for injection to be able to replicate the errors here and solve this?

I also encountered this problem.
I tested manually injecting the wajs code in chrome console, the steps are:
1) Login Whatsapp scanning QR code (whatsapp version > 2.3000)  (incognito mode, without other extensions)
2) Copy&Past wajs in console 

WPP.isInjected return False

It seems that the script wrongly set WPP.webpack.loaderType = "webpack" (webpackChunkwhatsapp_web_client)  instead of  new "meta"

**Comment by icleitoncosta** [comment] 2024-03-27 11:34
Hi, please test https://github.com/wppconnect-team/wa-js/pulls

**Comment by icleitoncosta** [comment] 2024-03-29 01:37
I will mark this issue as resolved, as I have already received feedback on other issues. Please reopen it if it has not been resolved.

**Closed by icleitoncosta** 2024-03-29 01:37 UTC
Labels: bug, needs triage
